<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Sortiran Transit</name>
   <tag></tag>
   <elementGuidId>e5c5c196-1419-4a60-a659-2a1cd0dbe643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/main/div/div/div[3]/div/div/div/div[3]/div/div/div/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss483 jss641 jss644 jss645 jss649 jss650 jss638 jss639 jss635</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pod/sortation/hub-transit-list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Sortiran Transit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;layout jss414 jss412&quot;]/div[@class=&quot;jss415 jss413&quot;]/main[@class=&quot;jss416&quot;]/div[@class=&quot;jss623 jss624 sidebar&quot;]/div[@class=&quot;jss446 jss448 jss426&quot;]/div[@class=&quot;jss700 jss701&quot;]/div[@class=&quot;jss702&quot;]/div[@class=&quot;jss703&quot;]/div[@class=&quot;jss704 jss655&quot;]/div[@class=&quot;jss700 jss701&quot;]/div[@class=&quot;jss702&quot;]/div[@class=&quot;jss703&quot;]/div[@class=&quot;jss704 jss655&quot;]/a[@class=&quot;jss483 jss641 jss644 jss645 jss649 jss650 jss638 jss639 jss635&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/main/div/div/div[3]/div/div/div/div[3]/div/div/div/a[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pod/sortation/hub-transit-list')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/a[4]</value>
   </webElementXpaths>
</WebElementEntity>
