<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>qcv2_updatebutton</name>
   <tag></tag>
   <elementGuidId>281adbcf-3939-4a7f-824d-db8ccdab2e90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[1]/div/section[2]/div[2]/div[2]/table/tbody/tr[2]/td[5]/a[1]/i</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/section[2]/div[2]/div[2]/table/tbody/tr[2]/td[5]/a[1]/i</value>
   </webElementProperties>
</WebElementEntity>
