<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eos_purchase_drop_down_button</name>
   <tag></tag>
   <elementGuidId>e50acc96-9e2b-4653-b49d-b144834fd857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div[1]/div[2]/div/div/div[1]/div/div/button[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/div[2]/div/div/div[1]/div/div/button[2]</value>
   </webElementProperties>
</WebElementEntity>
