<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eos_sales_menu_push_order_button</name>
   <tag></tag>
   <elementGuidId>27651fa7-b447-4605-a7f1-67ecda6eed51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;table-master-order&quot;]/tbody/tr[1]/td[11]/a[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;table-master-order&quot;]/tbody/tr[1]/td[11]/a[3]</value>
   </webElementProperties>
</WebElementEntity>
