<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar Surat Jalan Gabungan Sortir</name>
   <tag></tag>
   <elementGuidId>df1844a6-4b8e-4b7c-ac6f-3d6d75c4bf3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/main/div/div/div[4]/div/div/div/div[4]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss449 jss607 jss610 jss611 jss615 jss616 jss604 jss605 jss601</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pod/scan-out/bag-list</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar Surat Jalan Gabungan Sortir</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[3]/div[@class=&quot;layout jss380 jss378&quot;]/div[@class=&quot;jss381 jss379&quot;]/main[@class=&quot;jss382&quot;]/div[@class=&quot;jss589 jss590 sidebar&quot;]/div[@class=&quot;jss412 jss414 jss392&quot;]/div[@class=&quot;jss666 jss667&quot;]/div[@class=&quot;jss668&quot;]/div[@class=&quot;jss669&quot;]/div[@class=&quot;jss670 jss621&quot;]/div[@class=&quot;jss666 jss667&quot;]/div[@class=&quot;jss668&quot;]/div[@class=&quot;jss669&quot;]/div[@class=&quot;jss670 jss621&quot;]/a[@class=&quot;jss449 jss607 jss610 jss611 jss615 jss616 jss604 jss605 jss601&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/main/div/div/div[4]/div/div/div/div[4]/div/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pod/scan-out/bag-list')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[4]/div/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
