<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DOP211029NMCY4729</name>
   <tag></tag>
   <elementGuidId>492bc034-12e5-41da-bbd9-a1364d29bd30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div/main/div[2]/div/div[4]/div/div[3]/div/div/div[2]/table/tbody/tr/td[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss984</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DOP/2110/29/NMCY4729</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[3]/div[@class=&quot;layout jss380 jss378&quot;]/div[@class=&quot;jss381 jss379&quot;]/main[@class=&quot;jss382&quot;]/div[@class=&quot;jss383&quot;]/div[1]/div[@class=&quot;jss412 jss416 jss413&quot;]/div[@class=&quot;app-datatable-container&quot;]/div[@class=&quot;p-datatable p-component p-datatable-responsive p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body&quot;]/table[@class=&quot;p-datatable-scrollable-body-table app-datatable&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-datatable-row&quot;]/td[@class=&quot;text-left&quot;]/div[@class=&quot;ScanOutBagList_setCenter__19VRL&quot;]/div[@class=&quot;jss965 jss964&quot;]/span[@class=&quot;jss984&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div/main/div[2]/div/div[4]/div/div[3]/div/div/div[2]/table/tbody/tr/td[2]/div/div/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Surat Jalan'])[3]/following::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aksi'])[1]/following::span[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tgl Pengiriman'])[2]/preceding::span[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
