<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Lacak Resi_jss452</name>
   <tag></tag>
   <elementGuidId>cd3aa02f-8963-4cf2-81cb-04917641a31d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jss452</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;jss572 jss558&quot;]/div[@class=&quot;jss561 jss559&quot;]/div[@class=&quot;jss412 jss438 jss413 jss562 jss563 jss569 jss570&quot;]/div[@class=&quot;jss718 jss717 AppDialog_dialogTitle__2CDiA&quot;]/h6[@class=&quot;jss630 jss647&quot;]/div[@class=&quot;jss461 jss483 jss469&quot;]/div[@class=&quot;jss462 jss493&quot;]/button[@class=&quot;jss449 jss443 AppDialog_closeButton__2S4KG&quot;]/span[@class=&quot;jss448&quot;]/svg[@class=&quot;jss452&quot;]</value>
   </webElementProperties>
</WebElementEntity>
