<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_DO_HUB</name>
   <tag></tag>
   <elementGuidId>820cd043-8de7-4d43-8ac9-e694f5757416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang/Gerai'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DO_HUB</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;jss572 jss558&quot;]/div[@class=&quot;jss561 jss559&quot;]/div[@class=&quot;jss412 jss438 jss413 jss562 jss563 jss567 jss570&quot;]/div[@class=&quot;jss709 AppDialog_dialogContent__3jxow&quot;]/div[@class=&quot;app-datatable-container&quot;]/div[@class=&quot;p-datatable p-component p-datatable-scrollable&quot;]/div[@class=&quot;p-datatable-scrollable-wrapper&quot;]/div[@class=&quot;p-datatable-scrollable-view&quot;]/div[@class=&quot;p-datatable-scrollable-body&quot;]/table[@class=&quot;p-datatable-scrollable-body-table app-datatable&quot;]/tbody[@class=&quot;p-datatable-tbody&quot;]/tr[@class=&quot;p-datatable-row&quot;]/td[@class=&quot;text-center&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabang/Gerai'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User'])[1]/following::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bekasi Utara'])[2]/preceding::td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div[2]/table/tbody/tr/td</value>
   </webElementXpaths>
</WebElementEntity>
